version: '3.8'

services:
  db:
    image: 'postgres'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p2k8zR347
    volumes:
      - db:/var/lib/postgresql/data
    restart: always

  web:
    build: .
    ports:
      - 80:80
    command: bash -c "cd migrations && alembic upgrade head && cd ../products_aggregator && uvicorn api.views:app --host 0.0.0.0 --port 80 --workers 20"
    environment:
      - DATABASE_URL=postgresql://postgres:p2k8zR347@db:5432/postgres
    depends_on:
      - db
    restart: always

volumes:
  db: